#!/bin/bash

source FWBUILD

mkdir -p src
cd src

if [ -d $srcname ]; then
	echo "Source already present, skipping"
else
	git clone $source
fi

cd $srcname

# Prepare sources: checkout, apply any patches
prepare

# Build: Execute the build() function of the FWBUILD inside the docker container
declare -f build > .fwbuild
docker run --rm -it -v $PWD:$PWD -w $PWD $container bash -c "source .fwbuild && build"

# Package: Any post-build packaging, checksumming etc
package
